<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>SmartStandards.WebApiDependencies.CheapInitializer</AssemblyName>
    <RootNamespace>Microsoft.AspNetCore</RootNamespace>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>
  
  <PropertyGroup>
    <PackageId>SmartStandards.WebApiDependencies</PackageId>
    <Description>SmartStandards.WebApiDependencies</Description>
    <Product>SmartStandards.WebApiDependencies</Product>
    <Company>(public domain)</Company>
    <Copyright>SmartStandards</Copyright>
    <Version>10.0.11</Version>
    <AssemblyVersion>10.0.11</AssemblyVersion>
    <Authors>SmartStandards</Authors>
    <FileVersion>10.0.11</FileVersion>
    <PackageTags>AspNetCore Dependencies CheapInitializer</PackageTags>
    <PackageProjectUrl>https://github.com/SmartStandards/AspNetCoreTemplate</PackageProjectUrl>
    <RepositoryUrl>https://github.com/SmartStandards/AspNetCoreTemplate</RepositoryUrl>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>..\..\dist\bin-net10.0\SmartStandards.WebApiDependencies.CheapInitializer.xml</DocumentationFile>
    <OutputPath>..\..\dist\bin-net10.0\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>1701;1702;1591</NoWarn>
    <DefineConstants>TRACE;DEBUG;NET8</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <OutputPath>..\..\dist\bin-net10.0\</OutputPath>
    <DocumentationFile>..\..\dist\bin-net10.0\SmartStandards.WebApiDependencies.CheapInitializer.xml</DocumentationFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>1701;1702;1591</NoWarn>
    <DefineConstants>TRACE;NET8</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    
    <!-- IMPORTANT: this package is made for the ASP.NET Core ecosystem ONLY -->
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <!-- additional packages which are note implicitely provided by 'Microsoft.AspNetCore.App' -->
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Negotiate" Version="10.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.8" />

    <!-- intermediate (until we've completely switched to 'Microsoft.AspNetCore.OpenApi' -->
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="10.1.7" />

    <!-- intermediate (until we've completely switched to 'System.Text.Json' -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />

    <!-- 
    
    [implicitely provided by 'Microsoft.AspNetCore.App']

    <PackageReference Include=_"Microsoft.AspNetCore" Version="2.2.0" />
    <PackageReference Include=_"Microsoft.AspNetCore.Authentication.Negotiate" Version="5.0.17" />
    <PackageReference Include=_"Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="5.0.0" NoWarn="NU1605" />
    <PackageReference Include=_"Microsoft.AspNetCore.Cors" Version="2.2.0" />
    <PackageReference Include=_"Microsoft.AspNetCore.Http" Version="2.2.2" />
    <PackageReference Include=_"Microsoft.AspNetCore.Mvc" Version="2.2.0" />
    <PackageReference Include=_"Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include=_"Microsoft.AspNetCore.Mvc.Cors" Version="2.2.0" />
    
    [implicitely provided by .NET CORE]
    <PackageReference Include=_"System.Text.Encodings.Web" Version="6.0.0" />
    <PackageReference Include=_"System.Runtime" Version="4.3.1" />

    [old WCF-related reference]
    <PackageReference Include=_"System.ServiceModel.Primitives" Version="4.6.0" />
       
    -->

    <!-- Common packages from the 'SmartStandards' ecosystem -->
    
    <PackageReference Include="UJMW.DynamicClient" Version="5.5.1" />
    <PackageReference Include="UJMW.DynamicController" Version="5.5.1" />

    <PackageReference Include="SmartStandards.AuthTokenHandling" Version="5.1.0" />
    <PackageReference Include="SmartStandards.AuthTokenHandling.MvcSupport" Version="5.1.0" />

    <PackageReference Include="SmartAmbience" Version="2.5.1" />
    <PackageReference Include="SmartAmbience.MvcSupport" Version="2.5.1" />

    <PackageReference Include="SmartStandards.Essentials" Version="1.0.0" />

    <PackageReference Include="SmartStandards.Logging" Version="3.4.3" />
    <PackageReference Include="SmartStandards.Logging.AspSupport" Version="3.4.3" />

    <PackageReference Include="Snowflake44" Version="3.7.0" />
  
  </ItemGroup>

  <!-- IMPORTANT: this package is made for the ASP.NET Core ecosystem ONLY -->
  <Target Name="EnsureAspNetCore" BeforeTargets="Build">
    <Error Condition="!Exists('$(MSBuildProjectFullPath)') OR '$(TargetFrameworkIdentifier)' == '.NETFramework'" Text="This package requires ASP.NET Core (FrameworkReference to 'Microsoft.AspNetCore.App')." />
  </Target>

</Project>
